version: '1'

services:
  backend:
    build: ./
    container_name: 'backend'
    ports:
      - '8080:8080'
  frontend:
    build: ../frontend/
    container_name: 'frontend'
    ports:
      - '3000:3000'
    depends_on:
      - backend